[project]
name = "pkixwebadm"
version = "0.1.0"
dependencies = [
    "bcrypt",
    "fastapi",
    "jinja2",
    "pydantic",
    "pydantic-settings",
    "python-multipart",
    "uvicorn[standard]",
]

[tool.setuptools.packages.find]
include = ["pkixwebadm*"]
exclude = ["node_modules"]
